theme: jekyll-theme-slate
title: Project Portfolio
description: This is the project portfolio for Sigrid GÃ¥seidnes. I work as an analyst an team leader at innovation Norway. A government agency that finance innovation projects.
